# Generated by Django 4.2.15 on 2024-08-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivienda',
            name='calle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vivienda',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
